# download URLs: https://gist.github.com/wavezhang/ba8425f24a968ec9b2a8619d7c2d86a6

file_name: jdk-8u331-linux-x64.tar.gz
jdk8_linux_x64: "https://javadl.oracle.com/webapps/download/GetFile/1.8.0_331-b09/165374ff4ea84ef0bbd821706e29b123/linux-i586/{{file_name}}"

download_url: "{{jdk8_linux_x64}}"

download_path: "{{language_java}}/jdk-8u202-linux-x64.tar.gz"

download_script: |
  wget -c --no-cookies --no-check-certificate --header "Cookie: oraclelicense=accept-securebackup-cookie" {{download_url}}